# Generated by Django 2.0.3 on 2019-05-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190529_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='dinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='dinnerPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='dennerplatters',
            name='size',
        ),
        migrations.DeleteModel(
            name='dennerPlatters',
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.dinnerPrices'),
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sizes'),
        ),
    ]
