# Generated by Django 2.0.3 on 2019-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190530_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(to='orders.pastas'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='Default', max_length=64),
            preserve_default=False,
        ),
    ]
