# Generated by Django 2.0.3 on 2019-06-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190620_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinnerPlatters',
        ),
        migrations.AddField(
            model_name='order',
            name='dinnerPlatters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.dinnerPlatters'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pastas'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order_pizza'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.salads'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='subs',
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order_sub'),
        ),
    ]
