# Generated by Django 2.0.3 on 2019-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190620_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinnerPlatters',
        ),
        migrations.AddField(
            model_name='order',
            name='dinnerPlatters',
            field=models.ManyToManyField(to='orders.dinnerPlatters'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(to='orders.pastas'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='orders.order_pizza'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(to='orders.salads'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='subs',
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ManyToManyField(to='orders.order_sub'),
        ),
    ]
