# Generated by Django 2.0.3 on 2019-06-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190620_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),

        migrations.RemoveField(
            model_name='order',
            name='pastas',
            ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(through='orders.order_pasta', to='orders.pastas'),
        ),
        migrations.AddField(
            model_name='order_pasta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order_pasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pastas'),
        ),
    ]
