# Generated by Django 2.0.3 on 2019-07-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190620_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_pizza',
            name='sicilian',
        ),
        migrations.RemoveField(
            model_name='order_pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='order_pizza',
            name='orderInstance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_pizza',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='order',
            name='pizzas',
            ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(through='orders.order_pizza', to='orders.pizza'),
            preserve_default = False,
            )
    ]
