# Generated by Django 2.0.3 on 2019-07-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190707_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_pizza',
            name='orderInstance',
        ),
        migrations.RemoveField(
            model_name='order_pizza',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order_pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_pizza',
            name='sicilian',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_pizza',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.sizes'),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='order',
            name='pizzas'
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='orders.order_pizza'),
            preserve_default=False,
         )
    ]
