# Generated by Django 2.0.3 on 2019-07-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190708_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_dinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnerPlatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dinnerPlatters')),
            ],
        ),
        migrations.CreateModel(
            name='order_salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name = 'dinnerPlatters',

            ),
        migrations.AddField(
            model_name='order',
            name='dinnerPlatters',
            field=models.ManyToManyField(through='orders.order_dinnerPlatter', to='orders.dinnerPlatters'),
            ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
            ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(through='orders.order_salad', to='orders.salads'),
            ),
        
        migrations.AddField(
            model_name='order_salad',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order_salad',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salads'),
        ),
        migrations.AddField(
            model_name='order_dinnerplatter',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
