# Generated by Django 2.0.3 on 2019-07-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_made_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pasta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order_pasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.pastas'),
        ),
    ]
