# Generated by Django 2.0.3 on 2019-07-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190728_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pasta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order_pasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pastas'),
        ),
    ]
